version: '2'
services:
  server:
    build: .
    volumes:
      - ./data:/data
    mem_limit: 3G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
